# Generated by Django 2.1.7 on 2019-04-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsup', '0001_squashed_0007_auto_20170808_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='aperture',
        ),
        migrations.RemoveField(
            model_name='target',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='target',
            name='project',
        ),
        migrations.AlterField(
            model_name='params',
            name='aperture',
            field=models.CharField(choices=[('1m0', '1-meter'), ('2m0', '2-meter'), ('0m4', '0.4-meter'), ('any', 'Any'), ('sml', ' 1m and 0.4m only')], default='1m0', max_length=3),
        ),
        migrations.AlterField(
            model_name='params',
            name='filters',
            field=models.CharField(choices=[('B', 'Bessell-B'), ('I', 'Bessell-I'), ('R', 'Bessell-R'), ('V', 'Bessell-V'), ('H-Alpha', 'H Alpha'), ('H-Beta', 'H Beta'), ('OIII', 'OIII'), ('Y', 'PanSTARRS-Y'), ('zs', 'PanSTARRS-Z'), ('gp', 'SDSS-g&prime;'), ('ip', 'SDSS-i&prime;'), ('rp', 'SDSS-r&prime;'), ('up', 'SDSS-u&prime;'), ('solar', 'Solar (V+R)')], max_length=15, verbose_name='Filter name'),
        ),
        migrations.AlterField(
            model_name='target',
            name='best',
            field=models.BooleanField(default=False, verbose_name="Editor's pick"),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
