#!/bin/bash

# Substitute the prefix into the nginx configuration
echo "Running with PREFIX=${PREFIX}"
sed -i -e "s:@PREFIX@:${PREFIX}:g" /etc/nginx/nginx.conf

# Perform migrations and pull in fixtures
python /var/www/whatsup/manage.py migrate --noinput
#python /var/www/whatsup/manage.py loaddata full_catalogue.json

# Django static files
python /var/www/whatsup/manage.py collectstatic --noinput

# Run under supervisord
exec /usr/bin/supervisord -n -c /etc/supervisord.conf
